import type { SkillGroup } from "@/types";

export const skillGroups: SkillGroup[] = [
  {
    label: "AI Security",
    skills: [
      "LLM red-teaming",
      "Prompt injection detection & containment",
      "AI agent authorization",
      "Human-in-the-loop governance",
      "Hallucination mitigation",
      "AI output validation",
      "Adversarial input testing",
      "Privacy-preserving ML",
      "AI governance (ISO 42001)",
    ],
  },
  {
    label: "Cybersecurity",
    skills: [
      "SOC monitoring",
      "SIEM (Splunk)",
      "EDR (CrowdStrike Falcon)",
      "CloudSEK threat intelligence",
      "IOC/TTP analysis",
      "Penetration testing",
      "Vulnerability assessment",
      "Malware analysis",
      "Digital forensics",
      "Incident response",
      "DLP/CASB (Netskope)",
      "Nmap",
      "OWASP ZAP",
      "Nuclei",
    ],
  },
  {
    label: "GRC & Audit",
    skills: [
      "TPRM",
      "Risk assessment",
      "IT audit",
      "ITGC/ITAC",
      "ISO 27001 / 27701 / 42001",
      "NIST CSF",
      "SOC 2",
      "Statement of Applicability",
      "GDPR / DPDP / HIPAA",
      "BCP risk mapping",
      "MSA review",
      "Conformity assessment",
      "Vendor risk scoring",
    ],
  },
  {
    label: "Cloud & IAM",
    skills: [
      "Microsoft Azure",
      "Azure Arc",
      "Power Platform",
      "SharePoint",
      "Netskope CASB",
      "IAM",
      "DLP policy configuration",
      "Docker",
      "Kubernetes",
      "DevSecOps",
    ],
  },
  {
    label: "AI & Automation",
    skills: [
      "LLMs",
      "RAG",
      "AI agents",
      "LangChain",
      "LangGraph",
      "Prompt engineering",
      "Groq API",
      "Copilot APIs",
      "MCP",
      "n8n",
      "XGBoost",
      "LightGBM",
      "YOLOv8",
    ],
  },
  {
    label: "Engineering",
    skills: [
      "Python",
      "PowerShell",
      "JavaScript",
      "TypeScript",
      "Java",
      "C",
      "R",
      "SQL",
      "FastAPI",
      "Next.js",
      "React.js",
      "Node.js",
      "REST APIs",
      "PostgreSQL",
      "MongoDB",
      "Firebase",
      "Supabase",
      "Git",
      "Vercel",
    ],
  },
];

/** Flat list, used by the AI when asked broadly about the stack. */
export const allSkills = skillGroups.flatMap((g) => g.skills);
